// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT36w_ZbfbrHMW6PWJBwfGEYqEJj97qr4',
    appId: '1:750320766932:web:f9e893d7f582fbfbad1041',
    messagingSenderId: '750320766932',
    projectId: 'flutter-widgets-game',
    authDomain: 'flutter-widgets-game.firebaseapp.com',
    storageBucket: 'flutter-widgets-game.appspot.com',
    measurementId: 'G-NW1HSWTB59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC33rHVrgGGcv3fCsAtNxtkr_4nA_H1iK0',
    appId: '1:750320766932:android:75ab0f62f9138c89ad1041',
    messagingSenderId: '750320766932',
    projectId: 'flutter-widgets-game',
    storageBucket: 'flutter-widgets-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbp1FkHIvWNVcpJucuJtWfqkv4i2P9tuQ',
    appId: '1:750320766932:ios:4d641e71d66a4ac6ad1041',
    messagingSenderId: '750320766932',
    projectId: 'flutter-widgets-game',
    storageBucket: 'flutter-widgets-game.appspot.com',
    iosBundleId: 'com.example.flutterWidgetsMemoryTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbp1FkHIvWNVcpJucuJtWfqkv4i2P9tuQ',
    appId: '1:750320766932:ios:4d641e71d66a4ac6ad1041',
    messagingSenderId: '750320766932',
    projectId: 'flutter-widgets-game',
    storageBucket: 'flutter-widgets-game.appspot.com',
    iosBundleId: 'com.example.flutterWidgetsMemoryTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT36w_ZbfbrHMW6PWJBwfGEYqEJj97qr4',
    appId: '1:750320766932:web:bedc632c10270151ad1041',
    messagingSenderId: '750320766932',
    projectId: 'flutter-widgets-game',
    authDomain: 'flutter-widgets-game.firebaseapp.com',
    storageBucket: 'flutter-widgets-game.appspot.com',
    measurementId: 'G-PY8D9JP19H',
  );
}
